language: node.js
node.js:
  - v10.15.3
npm:
  - 6.4.1
sudo: false
notifications:
  - email: false
install:
  - npm i -g @adonisjs/cli
  - cd server && mv .env.example .env && npm install
script:
  - mkdir app/ethereum/build
  - npm run compile
  - adonis test
